# Generated by Django 6.0.5 on 2026-06-29 10:31

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_fix_audit_defaults"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to=apps.accounts.models.avatar_upload_to
            ),
        ),
    ]
