# Generated by Django 6.0.2 on 2026-06-09 09:06

import apps.campaigns.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("subject", models.CharField(max_length=998)),
                ("body_html", models.TextField(blank=True, default="")),
                ("body_text", models.TextField(blank=True, default="")),
                ("recipient_emails", models.TextField(blank=True, default="")),
                ("from_name", models.CharField(blank=True, max_length=255)),
                ("reply_to", models.EmailField(blank=True, max_length=254)),
                (
                    "recipient_context",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Per-recipient variable data (e.g., from CSV upload)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("sending", "Sending"),
                            ("sent", "Sent"),
                            ("paused", "Paused"),
                            ("failed", "Failed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("total_recipients", models.PositiveIntegerField(default=0)),
                ("sent_count", models.PositiveIntegerField(default=0)),
                ("open_count", models.PositiveIntegerField(default=0)),
                ("bounce_count", models.PositiveIntegerField(default=0)),
                ("spam_score", models.FloatField(blank=True, null=True)),
                (
                    "spam_risk",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="low",
                        max_length=10,
                    ),
                ),
                ("is_ab_test", models.BooleanField(default=False)),
                (
                    "ab_test_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("ab_test_duration_hours", models.PositiveIntegerField(default=2)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CampaignAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="campaign_attachments/%Y/%m/")),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                ("mime_type", models.CharField(blank=True, max_length=255)),
                ("file_size", models.PositiveIntegerField(default=0)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="CampaignVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=1)),
                ("subject", models.CharField(max_length=998)),
                ("body_html", models.TextField(blank=True, default="")),
                ("body_text", models.TextField(blank=True, default="")),
                ("percentage", models.PositiveIntegerField(default=10)),
                ("sent_count", models.PositiveIntegerField(default=0)),
                ("open_count", models.PositiveIntegerField(default=0)),
                ("bounce_count", models.PositiveIntegerField(default=0)),
                ("spam_score", models.FloatField(blank=True, null=True)),
                (
                    "spam_risk",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="low",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="EmailClickEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clicked_url", models.URLField(max_length=2048)),
                ("clicked_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="EmailEngagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipient_email", models.EmailField(max_length=254)),
                ("tracking_token", models.CharField(max_length=64, unique=True)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("clicked_at", models.DateTimeField(blank=True, null=True)),
                ("open_count", models.PositiveIntegerField(default=0)),
                ("click_count", models.PositiveIntegerField(default=0)),
                ("last_event_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Template name (e.g., 'Welcome Email', 'Monthly Newsletter')",
                        max_length=255,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True, help_text="Email subject line", max_length=998
                    ),
                ),
                (
                    "body_html",
                    models.TextField(blank=True, help_text="HTML version of the email"),
                ),
                (
                    "body_text",
                    models.TextField(blank=True, help_text="Plain text version"),
                ),
                (
                    "header_logo",
                    models.ImageField(
                        blank=True,
                        help_text="Logo/image for the email header",
                        upload_to="template_headers/",
                    ),
                ),
                (
                    "footer_logo",
                    models.ImageField(
                        blank=True,
                        help_text="Logo/image for the email footer",
                        upload_to="template_footers/",
                    ),
                ),
                (
                    "header_text",
                    models.CharField(
                        blank=True,
                        help_text="Text displayed next to header logo",
                        max_length=255,
                    ),
                ),
                (
                    "footer_text",
                    models.TextField(
                        blank=True, help_text="Text displayed in the email footer"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="System-defined default template that cannot be deleted",
                    ),
                ),
                (
                    "use_count",
                    models.PositiveIntegerField(
                        default=0, help_text="How many times this template was used"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailUnsubscribe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="TemplateImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cid_name",
                    models.CharField(
                        help_text="Content-ID name (e.g. profile.jpg, logo.png)",
                        max_length=255,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Image file to embed",
                        upload_to=apps.campaigns.models.template_image_upload_to,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable label (e.g. Profile Picture)",
                        max_length=255,
                    ),
                ),
            ],
        ),
    ]
