# Generated by Django 6.0.2 on 2026-06-09 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("automations", "0001_initial"),
        ("campaigns", "0001_initial"),
        ("senders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="senders.sender",
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="source_workflow",
            field=models.ForeignKey(
                blank=True,
                help_text="If set, this campaign was created by an automation workflow",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="campaigns",
                to="automations.workflow",
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campaigns",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="campaignattachment",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="campaigns.campaign",
            ),
        ),
        migrations.AddField(
            model_name="campaignvariant",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variants",
                to="campaigns.campaign",
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="winner_variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="won_campaigns",
                to="campaigns.campaignvariant",
            ),
        ),
        migrations.AddField(
            model_name="emailclickevent",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="click_events",
                to="campaigns.campaign",
            ),
        ),
        migrations.AddField(
            model_name="emailengagement",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="engagements",
                to="campaigns.campaign",
            ),
        ),
        migrations.AddField(
            model_name="emailengagement",
            name="campaign_variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="engagements",
                to="campaigns.campaignvariant",
            ),
        ),
        migrations.AddField(
            model_name="emailclickevent",
            name="engagement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="click_events",
                to="campaigns.emailengagement",
            ),
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_templates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="template",
            field=models.ForeignKey(
                blank=True,
                help_text="Template used as source for this campaign",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="campaigns",
                to="campaigns.emailtemplate",
            ),
        ),
        migrations.AddField(
            model_name="emailunsubscribe",
            name="campaign",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="unsubscribes",
                to="campaigns.campaign",
            ),
        ),
        migrations.AddField(
            model_name="templateimage",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="campaigns.emailtemplate",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="campaignvariant",
            unique_together={("campaign", "label")},
        ),
        migrations.AddIndex(
            model_name="emailengagement",
            index=models.Index(
                fields=["tracking_token"], name="campaigns_e_trackin_c92ded_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailengagement",
            index=models.Index(
                fields=["campaign", "recipient_email"],
                name="campaigns_e_campaig_73c08f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emailengagement",
            index=models.Index(
                fields=["recipient_email"], name="campaigns_e_recipie_25ca00_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailengagement",
            index=models.Index(
                fields=["sent_at"], name="campaigns_e_sent_at_d6ea5c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailengagement",
            index=models.Index(
                fields=["opened_at"], name="campaigns_e_opened__7074b5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailengagement",
            index=models.Index(
                fields=["clicked_at"], name="campaigns_e_clicked_f9ee45_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailclickevent",
            index=models.Index(
                fields=["campaign", "clicked_at"], name="campaigns_e_campaig_1feca4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailclickevent",
            index=models.Index(
                fields=["campaign", "clicked_url"],
                name="campaigns_e_campaig_e21924_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="emailtemplate",
            unique_together={("user", "name")},
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["user", "status", "-created_at"],
                name="campaigns_c_user_id_8121af_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["user", "-created_at"], name="campaigns_c_user_id_3d39ac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["status", "scheduled_at"], name="campaigns_c_status_4a521f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["sender", "status"], name="campaigns_c_sender__bbe3f8_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="emailunsubscribe",
            unique_together={("email", "campaign")},
        ),
        migrations.AlterUniqueTogether(
            name="templateimage",
            unique_together={("template", "cid_name")},
        ),
    ]
