# Generated by Django 6.0.2 on 2026-06-10 04:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automations", "0003_alter_workflownode_type"),
        ("campaigns", "0003_campaign_workspace_emailtemplate_workspace"),
        ("senders", "0002_initial"),
        ("workspaces", "0003_workspaceonboarding"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["workspace", "status", "-created_at"],
                name="campaigns_c_workspa_7de058_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["workspace", "scheduled_at"],
                name="campaigns_c_workspa_e4be0b_idx",
            ),
        ),
    ]
