# Generated by Django 6.0.2 on 2026-06-17 21:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0006_fix_audit_defaults"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="emailunsubscribe",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="EmailBounce",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("postdatead", models.DateTimeField(default=django.utils.timezone.now)),
                ("postdatebs", models.CharField(blank=True, default="", max_length=10)),
                ("posttime", models.TimeField(default=django.utils.timezone.now)),
                ("modifydatead", models.DateTimeField(blank=True, null=True)),
                (
                    "modifydatebs",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                ("modifytime", models.TimeField(blank=True, null=True)),
                ("email", models.EmailField(db_index=True, max_length=254)),
                (
                    "bounce_type",
                    models.CharField(
                        choices=[("hard", "Hard"), ("soft", "Soft")],
                        default="hard",
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bounces",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "modifyby",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "postby",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["email", "bounce_type"],
                        name="campaigns_e_email_6d83ea_idx",
                    )
                ],
                "unique_together": {("email", "campaign")},
            },
        ),
    ]
