# Generated by Django 6.0.2 on 2026-06-18 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0007_emailunsubscribe_updated_at_emailbounce"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="last_error",
            field=models.TextField(
                blank=True, default="", help_text="Last send failure reason"
            ),
        ),
    ]
