# Generated by Django 6.0.2 on 2026-06-26 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0008_add_campaign_last_error"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="emailbounce",
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name="emailbounce",
            name="campaigns_e_email_6d83ea_idx",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="last_error",
        ),
        migrations.RemoveField(
            model_name="emailunsubscribe",
            name="updated_at",
        ),
        migrations.DeleteModel(
            name="EmailBounce",
        ),
    ]
