# Generated by Django 6.0.2 on 2026-06-09 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StoragePlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "price_per_gb_monthly",
                    models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["price_per_gb_monthly"],
            },
        ),
        migrations.CreateModel(
            name="WorkspaceBilling",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("storage_used_mb", models.IntegerField(default=0)),
                ("storage_limit_mb", models.IntegerField(default=0)),
                ("billing_email", models.EmailField(blank=True, max_length=254)),
                (
                    "monthly_cost_estimate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "storage_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workspaces",
                        to="billing.storageplan",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Workspace billing",
            },
        ),
    ]
