# Generated by Django 6.0.2 on 2026-06-09 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contacts", "0001_initial"),
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contactlist",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact_lists",
                to="workspaces.workspace",
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="contact_list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacts",
                to="contacts.contactlist",
            ),
        ),
        migrations.AddField(
            model_name="contactsegment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact_segments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contacttag",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact_tags",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="contacts", to="contacts.contacttag"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="contactcustomfield",
            unique_together={("user", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="contactcustomfieldvalue",
            unique_together={("contact", "field")},
        ),
        migrations.AlterUniqueTogether(
            name="contacttag",
            unique_together={("user", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="contact",
            unique_together={("contact_list", "email")},
        ),
    ]
