# Generated by Django 6.0.2 on 2026-06-09 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0002_initial"),
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactcustomfield",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact_custom_fields",
                to="workspaces.workspace",
            ),
        ),
        migrations.AddField(
            model_name="contactsegment",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact_segments",
                to="workspaces.workspace",
            ),
        ),
        migrations.AddField(
            model_name="contacttag",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact_tags",
                to="workspaces.workspace",
            ),
        ),
    ]
