# Generated by Django 6.0.2 on 2026-06-10 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0003_contactcustomfield_workspace_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(
                fields=["contact_list", "email"], name="contacts_co_contact_434e63_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(
                fields=["is_active", "unsubscribed"],
                name="contacts_co_is_acti_17b504_idx",
            ),
        ),
    ]
