# Generated by Django 6.0.2 on 2026-06-14 11:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0006_backfill_null_workspace"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="contactcustomfield",
            name="unique_custom_field_per_workspace",
        ),
        migrations.RemoveConstraint(
            model_name="contactcustomfield",
            name="unique_custom_field_per_user",
        ),
        migrations.RemoveConstraint(
            model_name="contacttag",
            name="unique_tag_per_workspace",
        ),
        migrations.RemoveConstraint(
            model_name="contacttag",
            name="unique_tag_per_user",
        ),
        migrations.AlterUniqueTogether(
            name="contactcustomfield",
            unique_together={("user", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="contacttag",
            unique_together={("user", "name")},
        ),
    ]
