# Generated by Django 6.0.2 on 2026-06-14 12:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "contacts",
            "0007_remove_contactcustomfield_unique_custom_field_per_workspace_and_more",
        ),
        ("workspaces", "0007_remove_teaminvitation_notified_inviter"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="contactcustomfield",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="contacttag",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="contactcustomfield",
            constraint=models.UniqueConstraint(
                condition=models.Q(("workspace__isnull", False)),
                fields=("workspace", "name"),
                name="unique_custom_field_per_workspace",
            ),
        ),
        migrations.AddConstraint(
            model_name="contactcustomfield",
            constraint=models.UniqueConstraint(
                condition=models.Q(("workspace__isnull", True)),
                fields=("user", "name"),
                name="unique_custom_field_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="contacttag",
            constraint=models.UniqueConstraint(
                condition=models.Q(("workspace__isnull", False)),
                fields=("workspace", "name"),
                name="unique_tag_per_workspace",
            ),
        ),
        migrations.AddConstraint(
            model_name="contacttag",
            constraint=models.UniqueConstraint(
                condition=models.Q(("workspace__isnull", True)),
                fields=("user", "name"),
                name="unique_tag_per_user",
            ),
        ),
    ]
