# Generated by Django 6.0.5 on 2026-06-17 07:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0008_alter_contactcustomfield_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="modifyby",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="modifydatead",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="modifydatebs",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="contact",
            name="modifytime",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="postby",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="postdatead",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="contact",
            name="postdatebs",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="contact",
            name="posttime",
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="contactcustomfield",
            name="modifyby",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contactcustomfield",
            name="modifydatead",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contactcustomfield",
            name="modifydatebs",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="contactcustomfield",
            name="modifytime",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contactcustomfield",
            name="postby",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contactcustomfield",
            name="postdatead",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="contactcustomfield",
            name="postdatebs",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="contactcustomfield",
            name="posttime",
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="contactcustomfieldvalue",
            name="modifyby",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contactcustomfieldvalue",
            name="modifydatead",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contactcustomfieldvalue",
            name="modifydatebs",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="contactcustomfieldvalue",
            name="modifytime",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contactcustomfieldvalue",
            name="postby",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contactcustomfieldvalue",
            name="postdatead",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="contactcustomfieldvalue",
            name="postdatebs",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="contactcustomfieldvalue",
            name="posttime",
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="contactlist",
            name="modifyby",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contactlist",
            name="modifydatead",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contactlist",
            name="modifydatebs",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="contactlist",
            name="modifytime",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contactlist",
            name="postby",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contactlist",
            name="postdatead",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="contactlist",
            name="postdatebs",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="contactlist",
            name="posttime",
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="contactsegment",
            name="modifyby",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contactsegment",
            name="modifydatead",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contactsegment",
            name="modifydatebs",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="contactsegment",
            name="modifytime",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contactsegment",
            name="postby",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contactsegment",
            name="postdatead",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="contactsegment",
            name="postdatebs",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="contactsegment",
            name="posttime",
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="contacttag",
            name="modifyby",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contacttag",
            name="modifydatead",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contacttag",
            name="modifydatebs",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="contacttag",
            name="modifytime",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contacttag",
            name="postby",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contacttag",
            name="postdatead",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="contacttag",
            name="postdatebs",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="contacttag",
            name="posttime",
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
