# Generated by Django 6.0.2 on 2026-06-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_fix_audit_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacttag',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
