# Generated by Django 6.0.2 on 2026-06-26 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0012_remove_contactcustomfield_modifyby_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contacttag",
            name="name",
            field=models.CharField(max_length=80),
        ),
    ]
