# Generated by Django 6.0.2 on 2026-06-09 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("automations", "0001_initial"),
        ("contacts", "0001_initial"),
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflow",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workflows",
                to="workspaces.workspace",
            ),
        ),
        migrations.AddField(
            model_name="workflowedge",
            name="workflow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="edges",
                to="automations.workflow",
            ),
        ),
        migrations.AddField(
            model_name="workflowenrollment",
            name="contact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="contacts.contact",
            ),
        ),
        migrations.AddField(
            model_name="workflowenrollment",
            name="workflow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="automations.workflow",
            ),
        ),
        migrations.AddField(
            model_name="workflownode",
            name="workflow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nodes",
                to="automations.workflow",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="workflowedge",
            unique_together={("workflow", "from_node_id", "to_node_id", "condition")},
        ),
        migrations.AlterUniqueTogether(
            name="workflowenrollment",
            unique_together={("contact", "workflow")},
        ),
        migrations.AlterUniqueTogether(
            name="workflownode",
            unique_together={("workflow", "node_id")},
        ),
    ]
