# Generated by Django 6.0.2 on 2026-06-10 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automations", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflownode",
            name="type",
            field=models.CharField(
                choices=[
                    ("trigger", "Trigger"),
                    ("delay", "Delay"),
                    ("action", "Action"),
                    ("wait_until_condition", "Wait Until Condition"),
                    ("branch", "Branch (If/Else)"),
                    ("goal", "Goal (Stop on Conversion)"),
                ],
                max_length=20,
            ),
        ),
    ]
