# Generated by Django 6.0.5 on 2026-06-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automations", "0004_add_audit_mixin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflow",
            name="modifydatebs",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="postdatebs",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="workflowedge",
            name="modifydatebs",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="workflowedge",
            name="postdatebs",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="workflowenrollment",
            name="modifydatebs",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="workflowenrollment",
            name="postdatebs",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="workflownode",
            name="modifydatebs",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="workflownode",
            name="postdatebs",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
    ]
