# Generated by Django 6.0.2 on 2026-06-17 21:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automations", "0005_fix_audit_defaults"),
        ("contacts", "0010_fix_audit_defaults"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowenrollment",
            name="step_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="workflowenrollment",
            name="visited_nodes",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddIndex(
            model_name="workflowenrollment",
            index=models.Index(
                fields=["status", "next_execution_at"],
                name="automations_status_83e1c4_idx",
            ),
        ),
    ]
