# Generated by Django 6.0.2 on 2026-06-26 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("automations", "0006_workflowenrollment_step_count_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="workflowenrollment",
            name="automations_status_83e1c4_idx",
        ),
        migrations.RemoveField(
            model_name="workflowenrollment",
            name="step_count",
        ),
        migrations.RemoveField(
            model_name="workflowenrollment",
            name="visited_nodes",
        ),
    ]
