# Generated by Django 6.0.2 on 2026-06-09 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_id",
                    models.CharField(
                        help_text="Provider message ID", max_length=255),
                ),
                ("from_email", models.EmailField(max_length=254)),
                ("from_name", models.CharField(blank=True, max_length=255)),
                ("to_emails", models.JSONField(blank=True, default=list)),
                ("cc_emails", models.JSONField(blank=True, default=list)),
                ("bcc_emails", models.JSONField(blank=True, default=list)),
                ("subject", models.CharField(blank=True, max_length=998)),
                ("body_text", models.TextField(blank=True)),
                ("body_html", models.TextField(blank=True)),
                ("received_at", models.DateTimeField()),
                (
                    "is_incoming",
                    models.BooleanField(
                        default=True, help_text="True if received, False if sent"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, help_text="Soft delete flag"),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ai_summary",
                    models.TextField(
                        blank=True, help_text="AI summary of this individual message"
                    ),
                ),
                ("intent", models.CharField(blank=True, max_length=50)),
                ("urgency", models.CharField(blank=True, max_length=20)),
            ],
            options={
                "ordering": ["received_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailThread",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "thread_id",
                    models.CharField(
                        help_text="Provider thread/conversation ID", max_length=255
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=998)),
                (
                    "snippet",
                    models.TextField(
                        blank=True, help_text="Latest message preview"),
                ),
                (
                    "participants",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of email addresses in thread",
                    ),
                ),
                ("message_count", models.IntegerField(default=0)),
                (
                    "ai_summary",
                    models.TextField(
                        blank=True, help_text="AI-generated thread summary"
                    ),
                ),
                (
                    "intent",
                    models.CharField(
                        blank=True,
                        help_text="Detected intent: question, complaint, support, sales, etc.",
                        max_length=50,
                    ),
                ),
                (
                    "urgency",
                    models.CharField(
                        blank=True,
                        help_text="Detected urgency: low, medium, high, urgent",
                        max_length=20,
                    ),
                ),
                (
                    "is_flagged",
                    models.BooleanField(
                        default=False, help_text="Flagged for priority attention"
                    ),
                ),
                ("last_message_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-last_message_at", "-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ai_generated_body",
                    models.TextField(help_text="Original AI-generated reply"),
                ),
                (
                    "edited_body",
                    models.TextField(
                        blank=True, help_text="Human-edited version"),
                ),
                (
                    "final_body",
                    models.TextField(
                        blank=True, help_text="The version that was approved/sent"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_review", "Pending Review"),
                            ("edited", "Edited"),
                            ("approved", "Approved"),
                            ("saved", "Saved to Drafts"),
                            ("sent", "Sent"),
                            ("discarded", "Discarded"),
                        ],
                        default="pending_review",
                        max_length=20,
                    ),
                ),
                (
                    "feedback",
                    models.TextField(
                        blank=True, help_text="Human feedback on the draft"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_drafts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailInbox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("gmail", "Gmail"), ("outlook", "Outlook")],
                        max_length=20,
                    ),
                ),
                ("email_address", models.EmailField(max_length=254)),
                (
                    "provider_account_id",
                    models.CharField(
                        blank=True, help_text="User ID from provider", max_length=255
                    ),
                ),
                ("access_token", models.TextField(blank=True)),
                (
                    "refresh_token",
                    models.TextField(
                        blank=True,
                        help_text="Encrypted via set_token() — never read/write directly",
                    ),
                ),
                ("token_expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_sync_status",
                    models.CharField(
                        blank=True,
                        default="pending",
                        help_text="pending, success, error",
                        max_length=50,
                    ),
                ),
                ("last_sync_error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_inboxes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["email_address"],
            },
        ),
    ]
