# Generated by Django 6.0.2 on 2026-06-09 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inbox", "0001_initial"),
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailinbox",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_inboxes",
                to="workspaces.workspace",
            ),
        ),
        migrations.AddField(
            model_name="emaildraft",
            name="original_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="drafts",
                to="inbox.emailmessage",
            ),
        ),
        migrations.AddField(
            model_name="emailthread",
            name="inbox",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="threads",
                to="inbox.emailinbox",
            ),
        ),
        migrations.AddField(
            model_name="emailmessage",
            name="thread",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="inbox.emailthread",
            ),
        ),
        migrations.AddField(
            model_name="emaildraft",
            name="thread",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="drafts",
                to="inbox.emailthread",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="emailinbox",
            unique_together={("user", "email_address")},
        ),
        migrations.AlterUniqueTogether(
            name="emailthread",
            unique_together={("inbox", "thread_id")},
        ),
        migrations.AlterUniqueTogether(
            name="emailmessage",
            unique_together={("thread", "message_id")},
        ),
    ]
