# Generated by Django 6.0.2 on 2026-06-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inbox", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emaildraft",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_review", "Pending Review"),
                    ("edited", "Edited"),
                    ("approved", "Approved"),
                    ("sent", "Sent"),
                ],
                default="pending_review",
                max_length=20,
            ),
        ),
    ]
