# Generated by Django 6.0.2 on 2026-06-10 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inbox", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emailmessage",
            options={"ordering": ["-received_at"]},
        ),
        migrations.AddIndex(
            model_name="emailmessage",
            index=models.Index(
                fields=["thread", "received_at"], name="inbox_email_thread__654481_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailmessage",
            index=models.Index(
                fields=["is_incoming", "received_at"],
                name="inbox_email_is_inco_682dd9_idx",
            ),
        ),
    ]
