# Generated by Django 5.0.6 on 2026-06-13 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inbox", "0003_alter_emaildraft_status"),
        ("inbox", "0003_alter_emailmessage_options_and_more"),
    ]

    operations = []
