# Generated by Django 6.0.2 on 2026-06-12 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0003_alter_emaildraft_status'),
        ('inbox', '0003_alter_emailmessage_options_and_more'),
    ]

    operations = [
    ]
