# Generated by Django 6.0.2 on 2026-06-14 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inbox", "0004_merge_20260612_1208"),
        ("inbox", "0004_merge_20260612_1303"),
        ("inbox", "0004_merge_20260614_0544"),
    ]

    operations = []
