# Generated by Django 6.0.2 on 2026-06-14 12:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inbox", "0005_merge_20260614_1716"),
        ("workspaces", "0006_workspace_workspaces__name_5adeb1_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="emaildraft",
            index=models.Index(
                fields=["user", "status"], name="inbox_email_user_id_3ac61f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emaildraft",
            index=models.Index(
                fields=["original_message"], name="inbox_email_origina_0cd6c1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailinbox",
            index=models.Index(
                fields=["is_active", "last_sync_status"],
                name="inbox_email_is_acti_45ff82_idx",
            ),
        ),
    ]
