# Generated by Django 6.0.2 on 2026-06-15 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inbox", "0005_merge_20260614_1801"),
        ("inbox", "0006_emaildraft_inbox_email_user_id_3ac61f_idx_and_more"),
    ]

    operations = []
