# Generated by Django 6.0.2 on 2026-06-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inbox", "0006_emaildraft_inbox_email_user_id_3ac61f_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailmessage",
            name="is_read",
            field=models.BooleanField(
                default=False, help_text="Whether the message has been opened"
            ),
        ),
    ]
