# Generated by Codex on 2026-06-16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inbox", "0007_add_emailmessage_is_read"),
        ("inbox", "0007_merge_20260615_1306"),
    ]

    operations = []
