# Generated by Django 6.0.2 on 2026-06-17 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inbox", "0008_merge_20260616_0001"),
        ("inbox", "0009_fix_audit_defaults"),
    ]

    operations = []
