# Generated by Django 6.0.2 on 2026-06-17 21:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inbox", "0010_merge_20260618_0332"),
        ("workspaces", "0010_fix_audit_defaults"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="emailinbox",
            index=models.Index(
                fields=["workspace", "is_active"], name="inbox_email_workspa_f777a8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailinbox",
            index=models.Index(
                fields=["token_expires_at"], name="inbox_email_token_e_dc4ae7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailmessage",
            index=models.Index(
                fields=["is_deleted", "received_at"],
                name="inbox_email_is_dele_924d84_idx",
            ),
        ),
    ]
