# Generated by Django 6.0.2 on 2026-06-18 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inbox", "0011_emailinbox_inbox_email_workspa_f777a8_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailinbox",
            name="imap_password",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Fernet-encrypted IMAP/app password (base64-encoded) — separate from OAuth access_token",
            ),
        ),
    ]
