# Generated by Django 6.0.2 on 2026-06-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inbox", "0012_add_imap_password_field"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="emailinbox",
            name="inbox_email_workspa_f777a8_idx",
        ),
        migrations.RemoveIndex(
            model_name="emailinbox",
            name="inbox_email_token_e_dc4ae7_idx",
        ),
        migrations.RemoveIndex(
            model_name="emailmessage",
            name="inbox_email_is_dele_924d84_idx",
        ),
        migrations.AddField(
            model_name="emaildraft",
            name="ai_generated",
            field=models.BooleanField(
                default=False, help_text="Whether this draft was generated by AI"
            ),
        ),
        migrations.RemoveField(
            model_name="emailinbox",
            name="imap_password",
        ),
    ]
