# Generated by Django 6.0.2 on 2026-06-22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0010_fix_audit_defaults'),
        ('inbox', '0013_remove_emailinbox_inbox_email_workspa_f777a8_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaildraft',
            name='workspace',
            field=models.ForeignKey(
                blank=True,
                null=True,
                related_name='email_drafts',
                on_delete=django.db.models.deletion.CASCADE,
                to='workspaces.workspace',
            ),
        ),
        migrations.AddIndex(
            model_name='emaildraft',
            index=models.Index(fields=['user', 'status', 'workspace'], name='emaildraft_u_w_s_idx'),
        ),
        migrations.AddIndex(
            model_name='emaildraft',
            index=models.Index(fields=['workspace', 'status'], name='emaildraft_ws_status_idx'),
        ),
    ]