# Generated by Django 6.0.2 on 2026-06-22 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inbox", "0012_add_imap_password_field"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="emaildraft",
            name="inbox_email_user_id_3ac61f_idx",
        ),
    ]
