# Generated by Django 6.0.2 on 2026-06-26 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inbox", "0014_emaildraft_workspace"),
        ("inbox", "0015_intelligence_rule_action_activitylog"),
    ]

    operations = []
