# Generated by Django 6.0.2 on 2026-06-27 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inbox", "0016_merge_20260626_2235"),
    ]

    operations = []
