# Generated by Django 6.0.2 on 2026-06-27 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inbox", "0017_inbox_state_match"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="emaildraft",
            new_name="inbox_email_user_id_5f9bba_idx",
            old_name="emaildraft_u_w_s_idx",
        ),
        migrations.RenameIndex(
            model_name="emaildraft",
            new_name="inbox_email_workspa_67c63d_idx",
            old_name="emaildraft_ws_status_idx",
        ),
    ]
