# Generated by Django 6.0.2 on 2026-07-01 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0010_merge_20260629_1617'),
        ('inbox', '0018_rename_emaildraft_u_w_s_idx_inbox_email_user_id_5f9bba_idx_and_more'),
    ]

    operations = [
    ]
