# Generated by Django 6.0.2 on 2026-06-09 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("media_assets", "0001_initial"),
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="mediaasset",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media_assets",
                to="workspaces.workspace",
            ),
        ),
        migrations.AddField(
            model_name="mediafolder",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subfolders",
                to="media_assets.mediafolder",
            ),
        ),
        migrations.AddField(
            model_name="mediafolder",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="asset_folders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="mediafolder",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media_folders",
                to="workspaces.workspace",
            ),
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assets",
                to="media_assets.mediafolder",
            ),
        ),
        migrations.AddField(
            model_name="mediatag",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media_tags",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="assets", to="media_assets.mediatag"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="mediafolder",
            unique_together={("name", "parent", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="mediatag",
            unique_together={("name", "user")},
        ),
    ]
