# Generated by Django 6.0.5 on 2026-06-17 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media_assets", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediaasset",
            name="storage_backend",
            field=models.CharField(
                choices=[
                    ("local", "Local Storage"),
                    ("s3", "Amazon S3"),
                    ("r2", "Cloudflare R2"),
                    ("minio", "MinIO"),
                ],
                default="local",
                max_length=20,
            ),
        ),
    ]
