# Generated by Django 6.0.2 on 2026-06-09 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workspaces", "0002_workspace_plan_workspace_stripe_customer_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkspaceAPIKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Label to identify this key", max_length=255
                    ),
                ),
                ("prefix", models.CharField(editable=False, max_length=8, unique=True)),
                ("key_hash", models.CharField(editable=False, max_length=128)),
                (
                    "scopes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='List of permitted actions or "*" for all',
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workspace API key",
                "verbose_name_plural": "Workspace API keys",
                "ordering": ["-created_at"],
            },
        ),
    ]
