# Generated by Django 6.0.2 on 2026-06-14 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('source_type', models.CharField(choices=[('rss', 'RSS Feed'), ('api', 'API'), ('web', 'Web Scraper')], max_length=10)),
                ('url', models.URLField(max_length=500)),
                ('config_json', models.JSONField(blank=True, default=dict, help_text='Extra config like headers, params, selectors')),
                ('poll_interval_hours', models.PositiveIntegerField(default=6)),
                ('is_active', models.BooleanField(default=True)),
                ('last_fetched', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, default='📰', max_length=10)),
                ('color', models.CharField(blank=True, default='#06B6D4', max_length=7)),
                ('keywords', models.JSONField(blank=True, default=list, help_text='Keywords used to auto-classify content')),
                ('subscriber_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-subscriber_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FeedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=1000, unique=True)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('content_raw', models.TextField(blank=True)),
                ('content_cleaned', models.TextField(blank=True)),
                ('ai_summary', models.TextField(blank=True)),
                ('ai_categories', models.JSONField(blank=True, default=list)),
                ('trending_score', models.FloatField(default=0.0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('language', models.CharField(blank=True, default='en', max_length=10)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_items', to='trending.contentsource')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_items', to='trending.topic')),
            ],
            options={
                'ordering': ['-trending_score', '-published_at'],
            },
        ),
        migrations.CreateModel(
            name='UserActivityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inferred_keywords', models.JSONField(blank=True, default=list)),
                ('inferred_topic_ids', models.JSONField(blank=True, default=list)),
                ('last_analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trending_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User activity profiles',
            },
        ),
        migrations.CreateModel(
            name='UserFeedInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('saved', 'Saved as Draft'), ('bookmarked', 'Bookmarked'), ('dismissed', 'Dismissed')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feed_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_interactions', to='trending.feeditem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trending_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserTopicPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_auto_detected', models.BooleanField(default=False)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to='trending.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trending_topic_prefs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='feeditem',
            index=models.Index(fields=['-trending_score'], name='trending_fe_trendin_6c562a_idx'),
        ),
        migrations.AddIndex(
            model_name='feeditem',
            index=models.Index(fields=['topic', '-published_at'], name='trending_fe_topic_i_718612_idx'),
        ),
        migrations.AddIndex(
            model_name='feeditem',
            index=models.Index(fields=['is_duplicate'], name='trending_fe_is_dupl_d60c3b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userfeedinteraction',
            unique_together={('user', 'feed_item', 'interaction_type')},
        ),
        migrations.AlterUniqueTogether(
            name='usertopicpreference',
            unique_together={('user', 'topic')},
        ),
    ]
