# Generated by Django 6.0.2 on 2026-06-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trending', '0003_add_ready_draft_and_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeditem',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
