# Generated by Django 6.0.2 on 2026-06-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trending', '0005_rename_ready_draft_to_currents'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentitem',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
