# Generated by Django 6.0.2 on 2026-06-17 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trending', '0006_currentitem_metadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendingAutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platforms', models.JSONField(blank=True, default=list, help_text='List of platform strings to publish to')),
                ('schedule_interval', models.CharField(choices=[('hourly', 'Every Hour'), ('every_6h', 'Every 6 Hours'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=20)),
                ('auto_publish', models.BooleanField(default=False, help_text='Auto-publish to social media without review')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to='trending.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trending_automation_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trending Automation Rule',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'topic')},
            },
        ),
    ]
