# Generated by Django 6.0.5 on 2026-06-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trending", "0007_add_audit_mixin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentsource",
            name="modifydatebs",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="contentsource",
            name="postdatebs",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="currentitem",
            name="modifydatebs",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="currentitem",
            name="postdatebs",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="feeditem",
            name="modifydatebs",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="feeditem",
            name="postdatebs",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="topic",
            name="modifydatebs",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="topic",
            name="postdatebs",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="useractivityprofile",
            name="modifydatebs",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="useractivityprofile",
            name="postdatebs",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="userfeedinteraction",
            name="modifydatebs",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="userfeedinteraction",
            name="postdatebs",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="usertopicpreference",
            name="modifydatebs",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="usertopicpreference",
            name="postdatebs",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
    ]
