# Generated by Django 6.0.2 on 2026-06-17 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trending", "0008_add_currents_snapshot"),
        ("trending", "0008_fix_audit_defaults"),
    ]

    operations = []
