# Generated by Django 6.0.5 on 2026-06-29 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trending", "0008_add_currents_snapshot"),
        ("trending", "0008_fix_audit_defaults"),
    ]

    operations = []
