# Generated by Django 6.0.2 on 2026-06-22 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trending', '0008_add_currents_snapshot'),
        ('trending', '0009_add_trending_automation_rule_last_run_at'),
    ]

    operations = [
    ]
