# Generated by Django 6.0.2 on 2026-06-17 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trending", "0009_merge_20260618_0332"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="currentitem",
            name="modifyby",
        ),
        migrations.RemoveField(
            model_name="currentitem",
            name="modifydatead",
        ),
        migrations.RemoveField(
            model_name="currentitem",
            name="modifydatebs",
        ),
        migrations.RemoveField(
            model_name="currentitem",
            name="modifytime",
        ),
        migrations.RemoveField(
            model_name="currentitem",
            name="postby",
        ),
        migrations.RemoveField(
            model_name="currentitem",
            name="postdatead",
        ),
        migrations.RemoveField(
            model_name="currentitem",
            name="postdatebs",
        ),
        migrations.RemoveField(
            model_name="currentitem",
            name="posttime",
        ),
    ]
