# Generated by Django 6.0.2 on 2026-06-26 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trending", "0009_add_trending_automation_rule_last_run_at"),
        ("trending", "0010_remove_currentitem_modifyby_and_more"),
    ]

    operations = []
