# Generated by Django 6.0.2 on 2026-06-22 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trending', '0010_merge_20260622_1341'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='currentitem',
                    name='modifyby',
                ),
                migrations.RemoveField(
                    model_name='currentitem',
                    name='modifydatead',
                ),
                migrations.RemoveField(
                    model_name='currentitem',
                    name='modifydatebs',
                ),
                migrations.RemoveField(
                    model_name='currentitem',
                    name='modifytime',
                ),
                migrations.RemoveField(
                    model_name='currentitem',
                    name='postby',
                ),
                migrations.RemoveField(
                    model_name='currentitem',
                    name='postdatead',
                ),
                migrations.RemoveField(
                    model_name='currentitem',
                    name='postdatebs',
                ),
                migrations.RemoveField(
                    model_name='currentitem',
                    name='posttime',
                ),
            ],
        ),
    ]
