# Generated by Django 6.0.2 on 2026-07-01 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trending', '0009_merge_20260618_0332'),
        ('trending', '0011_merge_20260626_2235'),
    ]

    operations = [
    ]
