# Generated by Django 6.0.2 on 2026-07-01 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trending', '0012_merge_20260701_1632'),
        ('workspaces', '0012_alter_workspacepermission_module'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='currentitem',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='trendingautomationrule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='currentitem',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currents', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='currentssnapshot',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currents_snapshots', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='trendingautomationrule',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trending_automation_rules', to='workspaces.workspace'),
        ),
        migrations.AlterUniqueTogether(
            name='currentitem',
            unique_together={('user', 'workspace', 'feed_item')},
        ),
        migrations.AlterUniqueTogether(
            name='trendingautomationrule',
            unique_together={('user', 'workspace', 'topic')},
        ),
    ]
