# Generated by Django 6.0.5 on 2026-06-11 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("media_assets", "0002_initial"),
        ("workspaces", "0004_merge_20260610_1653"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CreativeContext",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(blank=True, max_length=255)),
                ("mission_statement", models.TextField(blank=True)),
                (
                    "goals",
                    models.TextField(
                        blank=True, help_text="Company goals and objectives"
                    ),
                ),
                (
                    "brand_voice",
                    models.TextField(
                        blank=True, help_text="Brand voice and personality guidelines"
                    ),
                ),
                (
                    "target_audience",
                    models.TextField(
                        blank=True, help_text="Primary target audience description"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creative_contexts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creative_contexts",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Creative Context",
                "verbose_name_plural": "Creative Contexts",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="CreativeStrategy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("campaign_goal", models.TextField()),
                ("target_audience", models.TextField(blank=True)),
                (
                    "tone_of_voice",
                    models.CharField(default="professional", max_length=50),
                ),
                ("generated_output", models.TextField(blank=True)),
                (
                    "llm_mode",
                    models.CharField(
                        blank=True,
                        help_text="Which LLM provider was used",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creative_strategies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creative_strategies",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Creative Strategy",
                "verbose_name_plural": "Creative Strategies",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CreativeStrategyAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "context_notes",
                    models.TextField(
                        blank=True,
                        help_text="User notes about this asset in relation to the strategy",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creative_strategies",
                        to="media_assets.mediaasset",
                    ),
                ),
                (
                    "strategy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linked_assets",
                        to="creative.creativestrategy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Strategy Asset Link",
                "verbose_name_plural": "Strategy Asset Links",
                "ordering": ["created_at"],
                "unique_together": {("strategy", "asset")},
            },
        ),
    ]
