# Generated by Django 6.0.5 on 2026-06-11 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creative", "0001_initial"),
        ("workspaces", "0004_merge_20260610_1653"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creativecontext",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="workspaces.workspace",
            ),
        ),
        migrations.AlterField(
            model_name="creativestrategy",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="workspaces.workspace",
            ),
        ),
    ]
