# Generated by Django 6.0.5 on 2026-06-12 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creative", "0002_alter_creativecontext_workspace_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="creativecontext",
            name="country",
            field=models.CharField(
                choices=[
                    ("nepal", "Nepal"),
                    ("india", "India"),
                    ("usa", "United States"),
                    ("uk", "United Kingdom"),
                    ("australia", "Australia"),
                    ("other", "Other"),
                ],
                default="nepal",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="creativecontext",
            name="cultural_context",
            field=models.TextField(
                blank=True,
                help_text="Cultural nuances, local festivals, regional preferences",
            ),
        ),
        migrations.AddField(
            model_name="creativecontext",
            name="industry",
            field=models.CharField(
                blank=True, help_text="Industry sector", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="creativestrategy",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_strategies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="creativestrategy",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="creativestrategy",
            name="rejection_reason",
            field=models.TextField(blank=True, help_text="Reason for rejection"),
        ),
        migrations.AddField(
            model_name="creativestrategy",
            name="scheduled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="creativestrategy",
            name="scheduled_platforms",
            field=models.JSONField(
                blank=True, default=list, help_text="Platforms to publish on"
            ),
        ),
        migrations.AddField(
            model_name="creativestrategy",
            name="strategy_type",
            field=models.CharField(
                choices=[
                    ("full_campaign", "Full Campaign Strategy"),
                    ("image_prompt", "Image Generation Prompt"),
                    ("logo_design", "Logo Design Brief"),
                    ("post_content", "Social Media Post"),
                    ("brand_identity", "Brand Identity Guide"),
                    ("content_calendar", "Content Calendar"),
                ],
                default="full_campaign",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="creativestrategyasset",
            name="platform",
            field=models.CharField(
                blank=True,
                help_text="Target platform for this asset (e.g. instagram, facebook)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="creativestrategyasset",
            name="scheduled_at",
            field=models.DateTimeField(
                blank=True, help_text="When to publish this asset", null=True
            ),
        ),
        migrations.AddField(
            model_name="creativestrategyasset",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Review"),
                    ("approved", "Approved for Use"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="creativestrategy",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending_review", "Pending Review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("published", "Published"),
                    ("archived", "Archived"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
