# Generated by Django 6.0.5 on 2026-06-12 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creative", "0003_creativecontext_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="creativecontext",
            name="brand_theme",
            field=models.TextField(
                blank=True,
                help_text="Brand theme, color palette, visual style, and design direction",
            ),
        ),
    ]
