# Generated by Django 6.0.5 on 2026-06-17 07:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creative", "0004_add_brand_theme"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="creativecontext",
            name="modifyby",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="creativecontext",
            name="modifydatead",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="creativecontext",
            name="modifydatebs",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="creativecontext",
            name="modifytime",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="creativecontext",
            name="postby",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="creativecontext",
            name="postdatead",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="creativecontext",
            name="postdatebs",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="creativecontext",
            name="posttime",
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="creativestrategy",
            name="modifyby",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="creativestrategy",
            name="modifydatead",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="creativestrategy",
            name="modifydatebs",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="creativestrategy",
            name="modifytime",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="creativestrategy",
            name="postby",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="creativestrategy",
            name="postdatead",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="creativestrategy",
            name="postdatebs",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="creativestrategy",
            name="posttime",
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="creativestrategyasset",
            name="modifyby",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="creativestrategyasset",
            name="modifydatead",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="creativestrategyasset",
            name="modifydatebs",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="creativestrategyasset",
            name="modifytime",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="creativestrategyasset",
            name="postby",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="creativestrategyasset",
            name="postdatead",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="creativestrategyasset",
            name="postdatebs",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="creativestrategyasset",
            name="posttime",
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="creativestrategy",
            name="strategy_type",
            field=models.CharField(
                choices=[
                    ("full_campaign", "Full Campaign Strategy"),
                    ("campaign_idea", "Marketing Campaign Ideas"),
                    ("brand_story", "Brand Storytelling Concepts"),
                    ("social_strategy", "Social Media Content Strategy"),
                    ("ad_copy", "Ad Copy Variations"),
                    ("product_launch", "Product Launch Ideas"),
                    ("tagline", "Taglines & Slogans"),
                    ("creative_angles", "Creative Angles"),
                    ("image_prompt", "Image Generation Prompt"),
                    ("logo_design", "Logo Design Brief"),
                    ("post_content", "Social Media Post"),
                    ("brand_identity", "Brand Identity Guide"),
                    ("content_calendar", "Content Calendar"),
                ],
                default="full_campaign",
                max_length=30,
            ),
        ),
    ]
