# Generated by Django 6.0.5 on 2026-06-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creative", "0005_add_audit_mixin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creativecontext",
            name="modifydatebs",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="creativecontext",
            name="postdatebs",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="creativestrategy",
            name="modifydatebs",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="creativestrategy",
            name="postdatebs",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="creativestrategyasset",
            name="modifydatebs",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="creativestrategyasset",
            name="postdatebs",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
    ]
