# Generated by Django 6.0.2 on 2026-06-09 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("social_accounts", "0001_initial"),
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialpost",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="social_posts",
                to="workspaces.workspace",
            ),
        ),
        migrations.AddField(
            model_name="socialanalytics",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analytics",
                to="social_accounts.socialpost",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="socialaccount",
            unique_together={("user", "platform", "account_id")},
        ),
    ]
