# Generated by Django 6.0.2 on 2026-06-09 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_studio', '0004_contentitem_platform_data_excelsheetimport_and_more'),
        ('social_accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='content_item',
            field=models.ForeignKey(blank=True, help_text='The Content Studio item this post was created from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_posts', to='content_studio.contentitem'),
        ),
    ]
