# Generated by Django 6.0.2 on 2026-06-10 04:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_accounts", "0002_initial"),
        ("workspaces", "0003_workspaceonboarding"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="socialpost",
            index=models.Index(
                fields=["account", "status", "scheduled_at"],
                name="social_acco_account_42325e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="socialpost",
            index=models.Index(
                fields=["workspace", "status"], name="social_acco_workspa_eab298_idx"
            ),
        ),
    ]
