# Generated by Django 6.0.2 on 2026-06-10 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social_accounts", "0003_add_content_item_fk"),
        ("social_accounts", "0003_socialpost_social_acco_account_42325e_idx_and_more"),
    ]

    operations = []
