# Generated by Django 6.0.2 on 2026-06-21 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AutoReplySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enable_auto_reply",
                    models.BooleanField(
                        default=False,
                        help_text="Enable automatic reply generation for incoming emails",
                    ),
                ),
                (
                    "confidence_threshold",
                    models.IntegerField(
                        default=70,
                        help_text="Minimum confidence score (0-100) to consider auto-replying",
                    ),
                ),
                (
                    "spam_risk_threshold",
                    models.CharField(
                        choices=[
                            ("Very Low", "Very Low"),
                            ("Low", "Low"),
                            ("Medium", "Medium"),
                            ("High", "High"),
                        ],
                        default="Medium",
                        help_text="Maximum spam risk level allowed for auto-reply (higher = more permissive)",
                        max_length=10,
                    ),
                ),
                (
                    "default_tone",
                    models.CharField(
                        choices=[
                            ("professional", "Professional"),
                            ("friendly", "Friendly"),
                            ("formal", "Formal"),
                            ("casual", "Casual"),
                        ],
                        default="professional",
                        help_text="Default tone for generated auto-replies",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auto_reply_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Auto Reply Settings",
                "verbose_name_plural": "Auto Reply Settings",
            },
        ),
    ]
