# Generated by Django 6.0.2 on 2026-06-22 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inbox", "0015_intelligence_rule_action_activitylog"),
        ("intelligence", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Rule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable rule name", max_length=100
                    ),
                ),
                (
                    "intent",
                    models.CharField(
                        choices=[
                            ("question", "Question"),
                            ("complaint", "Complaint"),
                            ("support", "Support Request"),
                            ("sales", "Sales Inquiry"),
                            ("meeting_request", "Meeting Request"),
                            ("information", "Information Request"),
                            ("introduction", "Introduction"),
                            ("feedback", "Feedback"),
                            ("other", "Other"),
                        ],
                        help_text="Email intent to match",
                        max_length=30,
                    ),
                ),
                (
                    "min_confidence",
                    models.IntegerField(
                        default=80,
                        help_text="Minimum confidence score (0-100) for this rule to fire",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "priority",
                    models.IntegerField(
                        default=0, help_text="Higher priority rules are evaluated first"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auto_reply_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Auto Reply Rule",
                "verbose_name_plural": "Auto Reply Rules",
                "ordering": ["-priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action_taken", models.CharField(max_length=30)),
                ("confidence", models.IntegerField(blank=True, null=True)),
                ("intent", models.CharField(blank=True, max_length=30)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "draft",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to="inbox.emaildraft",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="auto_reply_logs",
                        to="inbox.emailmessage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auto_reply_activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to="intelligence.rule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Auto Reply Activity Log",
                "verbose_name_plural": "Auto Reply Activity Logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("draft_reply", "Generate Draft Reply"),
                            ("flag_review", "Flag for Human Review"),
                            ("archive", "Archive"),
                            ("label", "Apply Label"),
                            ("ignore", "Ignore (No Action)"),
                        ],
                        help_text="Action to take when the parent rule matches",
                        max_length=20,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text='Label to apply (only for "Apply Label" action)',
                        max_length=50,
                    ),
                ),
                (
                    "tone_override",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("professional", "Professional"),
                            ("friendly", "Friendly"),
                            ("formal", "Formal"),
                            ("casual", "Casual"),
                            ("urgent", "Urgent"),
                        ],
                        help_text="Override default tone for draft_reply actions",
                        max_length=20,
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="intelligence.rule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Auto Reply Action",
                "verbose_name_plural": "Auto Reply Actions",
                "ordering": ["id"],
            },
        ),
    ]
