# Generated by Django 6.0.2 on 2026-06-22 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intelligence", "0002_intelligence_rule_action_activitylog"),
        ("workspaces", "0010_fix_audit_defaults"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitylog",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="auto_reply_activity_logs",
                to="workspaces.workspace",
            ),
        ),
        migrations.AddField(
            model_name="autoreplysettings",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="auto_reply_settings",
                to="workspaces.workspace",
            ),
        ),
        migrations.AddField(
            model_name="rule",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="auto_reply_rules",
                to="workspaces.workspace",
            ),
        ),
        migrations.AlterField(
            model_name="autoreplysettings",
            name="confidence_threshold",
            field=models.IntegerField(
                default=80,
                help_text="Minimum confidence score (0-100) to consider auto-replying",
            ),
        ),
    ]
