# Generated by Django 6.0.2 on 2026-06-09 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("social_accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Workspace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_workspaces",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TeamInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Admin"),
                            ("member", "Member"),
                        ],
                        default="member",
                        max_length=20,
                    ),
                ),
                ("token", models.CharField(editable=False, max_length=64, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "message",
                    models.TextField(blank=True, help_text="Optional personal message"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "invited_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=255)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workspace_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit log entry",
                "verbose_name_plural": "Audit logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkspaceStorageConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "backend",
                    models.CharField(
                        choices=[
                            ("local", "Local Disk"),
                            ("dia_s3", "DIA Managed S3"),
                            ("google_drive", "Google Drive"),
                            (
                                "s3_compatible",
                                "S3-Compatible (AWS S3 / R2 / MinIO / Wasabi / etc.)",
                            ),
                        ],
                        default="local",
                        max_length=20,
                    ),
                ),
                ("google_drive_client_id_encrypted", models.TextField(blank=True)),
                ("google_drive_client_secret_encrypted", models.TextField(blank=True)),
                ("google_drive_refresh_token_encrypted", models.TextField(blank=True)),
                ("google_drive_access_token", models.TextField(blank=True)),
                (
                    "google_drive_token_expiry",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "google_drive_folder_id",
                    models.CharField(blank=True, max_length=128),
                ),
                (
                    "google_drive_folder_name",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "google_drive_connected_email",
                    models.EmailField(blank=True, max_length=254),
                ),
                ("s3_endpoint_url", models.URLField(blank=True)),
                (
                    "s3_region",
                    models.CharField(blank=True, default="us-east-1", max_length=64),
                ),
                ("s3_bucket", models.CharField(blank=True, max_length=128)),
                ("s3_access_key_encrypted", models.TextField(blank=True)),
                ("s3_secret_key_encrypted", models.TextField(blank=True)),
                (
                    "s3_path_prefix",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "s3_public_base_url",
                    models.URLField(
                        blank=True,
                        help_text="Optional CDN/public base URL prepended to keys.",
                    ),
                ),
                ("s3_use_path_style", models.BooleanField(default=True)),
                (
                    "s3_provider_label",
                    models.CharField(
                        blank=True, default="S3-Compatible", max_length=64
                    ),
                ),
                (
                    "storage_used_mb",
                    models.IntegerField(
                        default=0, help_text="Latest calculated storage usage in MB"
                    ),
                ),
                (
                    "storage_last_checked_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("last_verified_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workspace",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="storage_config",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workspace storage config",
                "verbose_name_plural": "Workspace storage configs",
            },
        ),
        migrations.CreateModel(
            name="WorkspaceMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Admin"),
                            ("member", "Member"),
                        ],
                        default="member",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Workspace memberships",
                "unique_together": {("workspace", "user")},
            },
        ),
        migrations.CreateModel(
            name="WorkspacePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Admin"),
                            ("member", "Member"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        choices=[
                            ("campaigns", "Campaigns"),
                            ("contacts", "Contacts"),
                            ("social", "Social"),
                            ("media", "Media"),
                            ("workflows", "Workflows"),
                            ("inbox", "Inbox"),
                            ("content_studio", "Content Studio"),
                            ("workspace", "Workspace Settings"),
                            ("billing", "Billing"),
                            ("audit_log", "Audit Log"),
                            ("storage", "Storage"),
                            ("members", "Members"),
                            ("export", "Export Data"),
                        ],
                        max_length=30,
                    ),
                ),
                ("can_read", models.BooleanField(default=True)),
                ("can_create", models.BooleanField(default=False)),
                ("can_edit", models.BooleanField(default=False)),
                ("can_delete", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workspace permission",
                "verbose_name_plural": "Workspace permissions",
                "unique_together": {("workspace", "role", "module")},
            },
        ),
        migrations.CreateModel(
            name="WorkspaceSocialAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_links",
                        to="social_accounts.socialaccount",
                    ),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="added_workspace_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_accounts",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workspace social account",
                "verbose_name_plural": "Workspace social accounts",
                "unique_together": {("workspace", "account")},
            },
        ),
    ]
