# Generated by Django 6.0.2 on 2026-06-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacestorageconfig',
            name='google_sheets_access_token',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workspacestorageconfig',
            name='google_sheets_client_id_encrypted',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workspacestorageconfig',
            name='google_sheets_client_secret_encrypted',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workspacestorageconfig',
            name='google_sheets_connected_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='workspacestorageconfig',
            name='google_sheets_refresh_token_encrypted',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workspacestorageconfig',
            name='google_sheets_spreadsheet_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='workspacestorageconfig',
            name='google_sheets_spreadsheet_name',
            field=models.CharField(blank=True, default='Content Generator', max_length=255),
        ),
        migrations.AddField(
            model_name='workspacestorageconfig',
            name='google_sheets_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
