# Generated by Django 6.0.2 on 2026-06-10 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0002_workspace_plan_workspace_stripe_customer_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkspaceOnboarding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("connect_sender", models.BooleanField(default=False)),
                ("connect_sender_skipped", models.BooleanField(default=False)),
                ("import_contacts", models.BooleanField(default=False)),
                ("import_contacts_skipped", models.BooleanField(default=False)),
                ("create_campaign", models.BooleanField(default=False)),
                ("create_campaign_skipped", models.BooleanField(default=False)),
                ("connect_social", models.BooleanField(default=False)),
                ("connect_social_skipped", models.BooleanField(default=False)),
                ("dismissed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workspace",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workspace onboarding",
                "verbose_name_plural": "Workspace onboarding",
            },
        ),
    ]
