# Generated by Django 6.0.2 on 2026-06-10 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0002_add_google_sheets_fields"),
        ("workspaces", "0003_workspaceonboarding"),
    ]

    operations = []
