# Generated by Django 6.0.2 on 2026-06-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0004_merge_20260610_1653"),
    ]

    operations = [
        migrations.AddField(
            model_name="teaminvitation",
            name="notified_inviter",
            field=models.BooleanField(default=False),
        ),
    ]
