# Generated by Django 6.0.2 on 2026-06-14 12:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0005_teaminvitation_notified_inviter"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="workspace",
            index=models.Index(fields=["name"], name="workspaces__name_5adeb1_idx"),
        ),
        migrations.AddIndex(
            model_name="workspacemembership",
            index=models.Index(
                fields=["user", "workspace"], name="workspaces__user_id_413a11_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workspacemembership",
            index=models.Index(fields=["role"], name="workspaces__role_3baebc_idx"),
        ),
    ]
