# Generated by Django 6.0.2 on 2026-06-14 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0006_workspace_workspaces__name_5adeb1_idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teaminvitation",
            name="notified_inviter",
        ),
    ]
