# Generated by Django 6.0.5 on 2026-06-17 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0007_remove_teaminvitation_notified_inviter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspacestorageconfig",
            name="backend",
            field=models.CharField(
                choices=[("minio", "MinIO")], default="minio", max_length=20
            ),
        ),
    ]
