# Generated by Django 6.0.5 on 2026-06-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0009_add_audit_mixin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="modifydatebs",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="postdatebs",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="teaminvitation",
            name="modifydatebs",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="teaminvitation",
            name="postdatebs",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="workspace",
            name="modifydatebs",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="workspace",
            name="postdatebs",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="workspacemembership",
            name="modifydatebs",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="workspacemembership",
            name="postdatebs",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="workspaceonboarding",
            name="modifydatebs",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="workspaceonboarding",
            name="postdatebs",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="workspacepermission",
            name="modifydatebs",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="workspacepermission",
            name="postdatebs",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="workspacequota",
            name="modifydatebs",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="workspacequota",
            name="postdatebs",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="workspacesocialaccount",
            name="modifydatebs",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="workspacesocialaccount",
            name="postdatebs",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="workspacestorageconfig",
            name="modifydatebs",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="workspacestorageconfig",
            name="postdatebs",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
    ]
