# Generated by Django 6.0.2 on 2026-06-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0010_fix_audit_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspacepermission',
            name='module',
            field=models.CharField(choices=[('campaigns', 'Campaigns'), ('contacts', 'Contacts'), ('social', 'Social'), ('media', 'Media'), ('workflows', 'Workflows'), ('inbox', 'Inbox'), ('content_studio', 'Content Studio'), ('workspace', 'Workspace Settings'), ('billing', 'Billing'), ('audit_log', 'Audit Log'), ('members', 'Members'), ('export', 'Export Data')], max_length=30),
        ),
    ]
