# Generated by Django 6.0.2 on 2026-06-26 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0011_alter_workspacepermission_module"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspacepermission",
            name="module",
            field=models.CharField(
                choices=[
                    ("campaigns", "Campaigns"),
                    ("contacts", "Contacts"),
                    ("social", "Social"),
                    ("media", "Media"),
                    ("workflows", "Workflows"),
                    ("inbox", "Inbox"),
                    ("content_studio", "Content Studio"),
                    ("workspace", "Workspace Settings"),
                    ("billing", "Billing"),
                    ("audit_log", "Audit Log"),
                    ("storage", "Storage"),
                    ("members", "Members"),
                    ("export", "Export Data"),
                ],
                max_length=30,
            ),
        ),
    ]
