# Generated by Django 6.0.2 on 2026-06-09 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("content_studio", "0001_initial"),
        ("media_assets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contentitem",
            name="attachments",
            field=models.ManyToManyField(
                blank=True, related_name="content_items", to="media_assets.mediaasset"
            ),
        ),
        migrations.AddField(
            model_name="contentitem",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="content_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
