# Generated by Django 6.0.2 on 2026-06-09 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_studio', '0003_initial'),
        ('social_accounts', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='platform_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='ExcelSheetImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spreadsheet_id', models.CharField(help_text='Google Drive spreadsheet ID', max_length=255)),
                ('sheet_name', models.CharField(default='Sheet1', help_text='Name of the sheet/tab to read', max_length=255)),
                ('title', models.CharField(help_text='User-friendly name for this import source', max_length=255)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excel_sheet_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='contentitem',
            name='excel_source',
            field=models.ForeignKey(blank=True, help_text='The Excel sheet import this content was generated from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_items', to='content_studio.excelsheetimport'),
        ),
        migrations.CreateModel(
            name='UserGoogleSheetsToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_token', models.TextField()),
                ('access_token', models.TextField()),
                ('token_expiry', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_sheets_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExcelSheetRowLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField(help_text='The row number in the spreadsheet (1-indexed, including header)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('platform', models.CharField(blank=True, help_text='Target platform for this row', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='excel_row_logs', to='content_studio.contentitem')),
                ('import_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='row_logs', to='content_studio.excelsheetimport')),
                ('social_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='excel_row_logs', to='social_accounts.socialpost')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('import_source', 'row_number')},
            },
        ),
        migrations.CreateModel(
            name='UserGoogleSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spreadsheet_id', models.CharField(max_length=255)),
                ('sheet_name', models.CharField(default='Sheet1', max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_sheets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'spreadsheet_id')},
            },
        ),
    ]
