# Generated by Django 6.0.5 on 2026-06-17 07:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_studio", "0005_add_deleted_drive_sheet"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contentapproval",
            name="modifyby",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contentapproval",
            name="modifydatead",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contentapproval",
            name="modifydatebs",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="contentapproval",
            name="modifytime",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contentapproval",
            name="postby",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contentapproval",
            name="postdatead",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="contentapproval",
            name="postdatebs",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="contentapproval",
            name="posttime",
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="contentitem",
            name="modifyby",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contentitem",
            name="modifydatead",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contentitem",
            name="modifydatebs",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="contentitem",
            name="modifytime",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contentitem",
            name="postby",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contentitem",
            name="postdatead",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="contentitem",
            name="postdatebs",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="contentitem",
            name="posttime",
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="contentversion",
            name="modifyby",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contentversion",
            name="modifydatead",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contentversion",
            name="modifydatebs",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="contentversion",
            name="modifytime",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contentversion",
            name="postby",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contentversion",
            name="postdatead",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="contentversion",
            name="postdatebs",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="contentversion",
            name="posttime",
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="deleteddrivesheet",
            name="modifyby",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="deleteddrivesheet",
            name="modifydatead",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deleteddrivesheet",
            name="modifydatebs",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="deleteddrivesheet",
            name="modifytime",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deleteddrivesheet",
            name="postby",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="deleteddrivesheet",
            name="postdatead",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="deleteddrivesheet",
            name="postdatebs",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="deleteddrivesheet",
            name="posttime",
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="excelsheetimport",
            name="modifyby",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="excelsheetimport",
            name="modifydatead",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="excelsheetimport",
            name="modifydatebs",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="excelsheetimport",
            name="modifytime",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="excelsheetimport",
            name="postby",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="excelsheetimport",
            name="postdatead",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="excelsheetimport",
            name="postdatebs",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="excelsheetimport",
            name="posttime",
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="excelsheetrowlog",
            name="modifyby",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="excelsheetrowlog",
            name="modifydatead",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="excelsheetrowlog",
            name="modifydatebs",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="excelsheetrowlog",
            name="modifytime",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="excelsheetrowlog",
            name="postby",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="excelsheetrowlog",
            name="postdatead",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="excelsheetrowlog",
            name="postdatebs",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="excelsheetrowlog",
            name="posttime",
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="usergooglesheet",
            name="modifyby",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="usergooglesheet",
            name="modifydatead",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usergooglesheet",
            name="modifydatebs",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="usergooglesheet",
            name="modifytime",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usergooglesheet",
            name="postby",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="usergooglesheet",
            name="postdatead",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="usergooglesheet",
            name="postdatebs",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="usergooglesheet",
            name="posttime",
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="usergooglesheetstoken",
            name="modifyby",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="usergooglesheetstoken",
            name="modifydatead",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usergooglesheetstoken",
            name="modifydatebs",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="usergooglesheetstoken",
            name="modifytime",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usergooglesheetstoken",
            name="postby",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="usergooglesheetstoken",
            name="postdatead",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="usergooglesheetstoken",
            name="postdatebs",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="usergooglesheetstoken",
            name="posttime",
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
