# Generated by Django 6.0.5 on 2026-06-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_studio", "0006_add_audit_mixin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentapproval",
            name="modifydatebs",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="contentapproval",
            name="postdatebs",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="contentitem",
            name="modifydatebs",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="contentitem",
            name="postdatebs",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="contentversion",
            name="modifydatebs",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="contentversion",
            name="postdatebs",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="deleteddrivesheet",
            name="modifydatebs",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="deleteddrivesheet",
            name="postdatebs",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="excelsheetimport",
            name="modifydatebs",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="excelsheetimport",
            name="postdatebs",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="excelsheetrowlog",
            name="modifydatebs",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="excelsheetrowlog",
            name="postdatebs",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="usergooglesheet",
            name="modifydatebs",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="usergooglesheet",
            name="postdatebs",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="usergooglesheetstoken",
            name="modifydatebs",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="usergooglesheetstoken",
            name="postdatebs",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
    ]
