# Generated by Django 6.0.2 on 2026-06-09 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Sender",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_name", models.CharField(max_length=255)),
                ("from_email", models.EmailField(max_length=254)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("gmail", "Gmail / Google Workspace"),
                            ("outlook", "Outlook / Office 365"),
                            ("custom", "Custom SMTP"),
                        ],
                        default="gmail",
                        max_length=20,
                    ),
                ),
                ("smtp_host", models.CharField(max_length=255)),
                ("smtp_port", models.PositiveIntegerField(default=587)),
                ("username", models.CharField(max_length=255)),
                ("_password", models.TextField(db_column="password")),
                ("use_tls", models.BooleanField(default=True)),
                ("daily_limit", models.PositiveIntegerField(default=500)),
                (
                    "send_delay_seconds",
                    models.FloatField(
                        default=3.0,
                        help_text="Seconds to wait between each email send (rate limiting)",
                    ),
                ),
                ("emails_sent_today", models.PositiveIntegerField(default=0)),
                ("last_reset_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="senders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
