# Generated by Django 6.0.2 on 2026-06-09 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("senders", "0001_initial"),
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sender",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="senders",
                to="workspaces.workspace",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="sender",
            unique_together={("user", "from_email")},
        ),
    ]
