# Generated by Django 5.0.6 on 2026-06-09 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("senders", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sender",
            name="reply_to",
            field=models.EmailField(
                blank=True, help_text="Optional reply-to address", max_length=254
            ),
        ),
    ]
