# Generated by Django 6.0.2 on 2026-06-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("senders", "0003_add_reply_to_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="sender",
            name="last_verified_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the SMTP connection was last successfully tested",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sender",
            name="is_active",
            field=models.BooleanField(
                default=False, help_text="Manually toggled on/off by user"
            ),
        ),
        migrations.AlterField(
            model_name="sender",
            name="is_verified",
            field=models.BooleanField(
                default=False,
                help_text="Set to True only after successful SMTP connection test",
            ),
        ),
    ]
