# Generated by Django 6.0.2 on 2026-06-22 20:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("senders", "0006_fix_audit_defaults"),
        ("workspaces", "0010_fix_audit_defaults"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="sender",
            unique_together={("user", "workspace", "from_email")},
        ),
    ]
