# Generated by Django 6.0.2 on 2026-06-09 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("facebook", "Facebook"),
                            ("instagram", "Instagram"),
                            ("twitter", "X (Twitter)"),
                            ("linkedin", "LinkedIn"),
                            ("tiktok", "TikTok"),
                            ("youtube", "YouTube"),
                        ],
                        max_length=20,
                    ),
                ),
                ("account_name", models.CharField(max_length=255)),
                ("account_id", models.CharField(blank=True, max_length=255)),
                ("access_token", models.TextField(blank=True)),
                ("refresh_token", models.TextField(blank=True)),
                ("token_expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["platform", "account_name"],
                "unique_together": {("user", "platform", "account_id")},
            },
        ),
        migrations.CreateModel(
            name="SocialPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("facebook", "Facebook"),
                            ("instagram", "Instagram"),
                            ("twitter", "X (Twitter)"),
                            ("linkedin", "LinkedIn"),
                            ("tiktok", "TikTok"),
                            ("youtube", "YouTube"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, help_text="Post caption / body text"),
                ),
                (
                    "media_urls",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of media file URLs or paths",
                    ),
                ),
                (
                    "link_url",
                    models.URLField(blank=True, help_text="Link to include in post"),
                ),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("publishing", "Publishing"),
                            ("published", "Published"),
                            ("failed", "Failed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "platform_post_id",
                    models.CharField(
                        blank=True,
                        help_text="ID returned by platform after publishing",
                        max_length=255,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="social.socialaccount",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-scheduled_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SocialMediaAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
                ("impressions", models.IntegerField(default=0)),
                ("reach", models.IntegerField(default=0)),
                ("likes", models.IntegerField(default=0)),
                ("shares", models.IntegerField(default=0)),
                ("comments", models.IntegerField(default=0)),
                ("clicks", models.IntegerField(default=0)),
                ("engagement_rate", models.FloatField(default=0.0)),
                ("followers_gained", models.IntegerField(default=0)),
                ("followers_lost", models.IntegerField(default=0)),
                (
                    "raw_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Raw API response for debugging",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="social.socialpost",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Social media analytics",
                "ordering": ["-fetched_at"],
            },
        ),
    ]
