# Generated by Django 5.0.6 on 2026-06-13 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("draft_created", "AI Draft Created"),
                            ("campaign_sent", "Campaign Sent"),
                            ("campaign_completed", "Campaign Completed"),
                            ("sync_completed", "Sync Completed"),
                            ("sync_failed", "Sync Failed"),
                            ("auto_reply_draft", "Auto-Reply Draft Created"),
                            ("campaign_failed", "Campaign Failed"),
                            ("sender_issue", "Sender Issue"),
                            ("dns_audit_completed", "DNS Audit Completed"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("action_url", models.CharField(blank=True, max_length=500)),
                ("read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "read"], name="notificatio_user_id_878a13_idx"
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="notificatio_user_id_c62b26_idx",
                    ),
                ],
            },
        ),
    ]
